"""update users

Revision ID: bf7818149281
Revises: 885c85ef6e65
Create Date: 2026-01-27 00:04:25.507196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf7818149281'
down_revision: Union[str, None] = '885c85ef6e65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=True))
    op.drop_column('users', 'fist_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fist_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
